name: Build and Test

on:
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Run setup.bat
        run: |
          ./setup.bat
        shell: cmd

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - uses: ZedThree/clang-tidy-review@v0.14.0
        id: review

      - uses: ZedThree/clang-tidy-review/upload@v0.14.0
        id: upload-review

      - if: steps.review.outputs.total_comments > 0
        run: exit 1

      - name: Build solution
        run: |
          msbuild Quirk.sln /p:Configuration=Release
        shell: cmd