name: Build and Test

on:
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Run setup.bat
        run: |
          ./setup.bat
        shell: cmd

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build solution
        run: |
          msbuild Quirk.sln /p:Configuration=Release
        shell: cmd

      - name: Run clang-tidy
        run: |
          clang-tidy Quirk/engine/*.cpp Quirk/engine/*.hpp Quirk/editor/*.cpp Quirk/editor/*.hpp Quirk/engine/*.inl Quirk/editor/*.inl -- -std=c++20
        shell: cmd

