name: Build and Test

on:
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install clang-format
        run: choco install llvm -y
        shell: cmd

      - name: Apply clang-format
        run: |
          @echo off
          for /f "delims=" %%i in ('git ls-files engine\*.cpp engine\*.h editor\*.cpp editor\*.h') do clang-format -i -style="{BasedOnStyle: Google, IndentWidth: 2, ColumnLimit: 80, AllowShortIfStatementsOnASingleLine: false}" %%i
        shell: cmd

      - name: Check for unformatted code
        run: git diff --exit-code
        shell: cmd

      - name: Run setup.bat
        run: ./setup.bat
        shell: cmd

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build solution
        run: msbuild Quirk.sln /p:Configuration=Release
        shell: cmd
